### ISSUE TITLE
[BUG] Error: spawn EINVAL

### ISSUE THREAD

**Issue by Badisi** [prebuild/prebuildify#83]
### Issue

I'm playing with the following github action:
```yaml
  prebuild:
    runs-on: ${{ matrix.os }}
    ...
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        architecture: ${{ matrix.arch }}
    ...
    - name: Prebuild
      run: prebuildify --target 12.0.0 --napi --strip
```
The main idea is to run **prebuildify** on `macos-latest:x64`, `ubuntu-latest:x64`, `windows-latest:x64` and `windows-latest:x86`.

Everything works fine except for the `windows-latest:x86` where I get the following issue:
```js
node:internal/child_process:414
    throw errnoException(err, 'spawn');
    ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at Object.spawn (node:child_process:761:9)
    at D:\a\my-project\node_modules\prebuildify\index.js:230:22
    at D:\a\my-project\node_modules\mkdirp-classic\index.js:30:20
    at FSReqCallback.oncomplete (node:fs:192:23) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
```

### Investigation

The code in `prebuildify index.js:230` is:
```js
var child = proc.spawn(opts.nodeGyp, args, {
  cwd: opts.cwd,
  env: opts.env,
  stdio: opts.quiet ? 'ignore' : 'inherit'
})
```

After debugging I can see that the actual value used for `opts.nodeGyp` is "**node-gyp.cmd**":
```
{
  ...
  stdio: 'inherit',
  args: [
    'node-gyp.cmd',
    'rebuild',
    '--target=12.0.0',
    '--devdir=C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\prebuildify\\node',
    '--arch=ia32',
    '--release'
  ],
  detached: false,
  envPairs: [
    ...,
    ... 98 more items
  ],
  file: 'node-gyp.cmd',
  windowsHide: false,
  windowsVerbatimArguments: false
}
```

### Solution

There seems to have some issues with `spawn` on Windows and most of the time people suggests to use `shell: true` to solve it.

So I monkey patched the previous code in prebuildify like this:
```js
var child = proc.spawn(opts.nodeGyp, args, {
  shell: true,
  cwd: opts.cwd,
  env: opts.env,
  stdio: opts.quiet ? 'ignore' : 'inherit'
})
```
and it indeed solved the issue.
